### ISSUE TITLE
So what is the command to launch from command pallete?

### ISSUE THREAD

**Issue by talamaska** [ericbiewener/vscode-vandelay#1]
Pardon me, probably I'm blind or something, but didn't find the list of commands that I can use to leverage the importing from the command pallete.

**Comment by ericbiewener** [comment]
The commands are listed in the documentation for the language plugin that you're using:

- [JavaScript](https://github.com/ericbiewener/vscode-vandelay-js#commands)
- [Python](https://github.com/ericbiewener/vscode-vandelay-py#commands)

**Comment by ericbiewener** [comment]
Right, the core Vandelay extension requires plugins for the language you want to use. See [How to Use](https://github.com/ericbiewener/vscode-vandelay#how-to-use).
