### ISSUE TITLE
Regarding Python infrastructure

### ISSUE THREAD

**Issue by lig** [ericbiewener/vscode-vandelay#12]
I have some questions after reading this project's description regarding the level it integrates with the common Python infrastructure.

- [ ] Is `isort` supported for ordering imports?
- [ ] Does `vandelay` correctly support imports like below?
```
import os  # autoimported
import urllib.request  # autoimported

urllib.request.urlopen(...)
os.path.join(...)
```
- [ ] Could `vandelay` be configured to be executed from a virtualenv and thus to respect its `sys.path`?
- [ ] Are there any plans to integrate common shorthands like below?
```
import numpy as np
import sqlalchemy as sa
```

I would say it will be useful to have answers to these questions available in the readme.

Thanks and keep up the good work!

**Comment by ericbiewener** [comment]
There is no `isort` integration, but there is a lot of import order logic built in that is described [here](https://github.com/ericbiewener/vscode-vandelay#importgroups-arraystring-js--arrayarraystring-py). It would indeed support the `os` and `urllib` import examples you gave.

Regarding virtrualenv execution, can you elaborate a bit more? The `vandelay-py.js` configuration file allows for a [`processImportPath()`](https://github.com/ericbiewener/vscode-vandelay#processimportpathimportpath-string-absimportpath-string-activefilepath-string-projectroot-string-string) function that lets you modify the import path that will be written to a file. Perhaps this solves the use-case you're imagining.

Finally, `import ... as ...` syntax is not currently supported, and that's an oversight that I'll start working on. I'll leave this issue open until that is released.

**Comment by ericbiewener** [comment]
Finally got around to releasing a fix for the `import as` python syntax. Required a bit of a refactor but the result is a much improved underlying data structure!

**Comment by ericbiewener** [comment]
To clarify, you would use the new [`processImportName`](https://github.com/ericbiewener/vscode-vandelay#processimportnameimportname-string-importpath-string-absimportpath-string-activefilepath-string-projectroot-string-isdefault-boolean-string) configuration hook to accomplish the `import as` syntax. The documentation has an example.
