### ISSUE TITLE
This is not a issue report, just wanna appreciate your work.

### ISSUE THREAD

**Issue by bearmc27** [ericbiewener/vscode-vandelay#13]
As title said, this is not a issue report and I just wanna appreciate your work.

(Warning: Bad Grammar)

I have started ReactJS programming for my work and personal projects for a month. I was not a front-end guy but more of a back-end guy so JavaScript and all those non strong typing language somewhat scares me a bit. Not because of the syntax, but the lack of IDE/Editor support on intellisense and all other feature that increase productivity. 

I have be facing a lot of problem while coding JavaScript (No TypeScript) with VSCode like intellisense, suggestions, linting, and syntax highlight. Most of those problems are easy enough to fix with existing tools. But one thing, and the last thing for me, is the auto-importing which I have never settle down to any tool or extension. I just cannot accept the outcome of other tools. Some are good on performance but are limited on feature. Some cover a lot of good features but are slow and unstable.

I basically installed and tried every single extension one by one, with the searching keyword "auto" "import" "js" and you know what..... I finally found it, that's Vandelay. The well balance between performance and feature (tbh I think vandelay cover all of the feature I needed), with good documenting (which is lacking in most of other extensions). As just a small part of the programmer world, I would like to thank you for your work and time spent on such a great tool.

Label this issue as "wontfix" would be great.

**Comment by ericbiewener** [comment]
Glad you're finding it so helpful, and thanks for the encouraging feedback!
