### ISSUE TITLE
Add Option to disable Suggestions

### ISSUE THREAD

**Issue by rafellerc** [ericbiewener/vscode-vandelay#23]
Could you add an option to disable Vandelay's suggestions or at least move them to the bottom of the suggestion list when typing? In my workflow the useful suggestion I normally use are being drowned by import suggestions:

Nice work by the way!

**Comment by ericbiewener** [comment]
Unfortunately VS Code doesn't give me any control over where the suggestions should appear in the list. I've just published an update that lets you [turn off the suggestions](https://github.com/ericbiewener/vscode-vandelay#providecompletions-boolean).

**Comment by eqperes** [comment]
I see the issue is already closed but IMHO being able to move vandelay's suggestions to the bottom of the list would greatly improve the experience. Would it be possible to create an issue on VSCode repository about that? 
Could you refer us to the API of the editor suggestions?
