### ISSUE TITLE
Differences from import-js

### ISSUE THREAD

**Issue by brummelte** [ericbiewener/vscode-vandelay#25]
I've just started using this extension and it seems to work better than import-js (https://github.com/Galooshi/import-js and https://github.com/dabbott/vscode-import-js).

It might make sense to write a short paragraph into the readme about the differences between the projects.

One great difference for me is analyzing the rest of the projects imports and using those as a reference.

**Comment by ericbiewener** [comment]
Beyond simply trying that package when I first switched to VS Code and finding that it didn't really work (can't remember the details), I don't really know the difference :)

If this package and import-js had large community uptake and confusion was being expressed, I think your suggestion would be warranted. Cool to hear that you've found value in Vandelay beyond simply the code generation part of it!
