### ISSUE TITLE
Babel macros are not working

### ISSUE THREAD

**Issue by brummelte** [ericbiewener/vscode-vandelay#26]
If I try to import gql, it will not include the `.macro`.

Result:
`import gql from "graphql-tag";`

Correct result:
`import gql from "graphql-tag.macro";`

Using processImportPath to fix this does not work either. It just ignores what I return from the function.

**Comment by ericbiewener** [comment]
Looks like node modules weren't getting run through the `processImportPath` hook. I've released a new version with that fixed.

**Comment by brummelte** [comment]
Thank you.

`processImportPath` works now, but the `.macro` is still removed from the absImportPath even though it should not.

Package name is [graphql-tag.macro](https://www.npmjs.com/package/graphql-tag.macro). But it gets imported without the `.macro`.

At least I can temporarily work around it for now with this config:

```javascript
module.exports = {
    // …
    processImportPath: (importPath, absImportPath) =>
        absImportPath === "graphql-tag" ? "graphql-tag.macro" : null,
};
```

**Comment by brummelte** [comment]
Can you reopen this issue, or should I create a new one?

**Comment by ericbiewener** [comment]
Just published a new version that preserves `.macro` extensions.
