### ISSUE TITLE
command 'vandelay.*' not found

### ISSUE THREAD

**Issue by zrebie** [ericbiewener/vscode-vandelay#28]
Eventhough the flask8 and plugin is configured and filling the imports works, the commands does not work:
command 'vandelay.removeUnusedImports' not found
command 'vandelay.importUndefinedVariables' not found

**Comment by ericbiewener** [comment]
Can you provide a test repo I can look at? It's strange that you're getting those errors when some of the commands work -- I'd expect all or nothing for error messages like that.
