### ISSUE TITLE
Access import name in processImportPath

### ISSUE THREAD

**Issue by jsangmeister** [ericbiewener/vscode-vandelay#31]
Would it be possible to add the import name as an additional argument to the function `processImportPath`? I'm exporting my python classes via an `__init__.py` and want to import them from there instead of their actual module, so I want to check in the `processImportPath` if the module is exported and remove the module name from the import path if that's the case. Alternatively, do you know a better solution for this?

**Comment by ericbiewener** [comment]
Will look into it this weekend.

**Comment by ericbiewener** [comment]
Ok, the call to `processImportPath` was previously running when assembling the list of available imports -- this meant it got called on every potential import. I think that was a mistake. I've now changed it to only run on the import path for the selected import. The consequence of this is that when viewing your list of imports, the dot-path that appears under the main name will not have been run through this function yet. That's arguably a benefit -- it will show you the more precise location of the import.

Could you test out the attached file? [Here are the instructions](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) for installing extensions from `*.vsix` files. I generally like to install a new version and actually use it at work for a day or two before releasing it, but I'm not writing any Python these days.

[vandelay-4.4.0.vsix.zip](https://github.com/ericbiewener/vscode-vandelay/files/4435832/vandelay-4.4.0.vsix.zip)

**Comment by jsangmeister** [comment]
Thanks for the update! Unfortunately, I'm not seeing how this helps with my issue since I still cannot access the imported class in `processImportPath`. Or did you have another way in mind?

An alternative would be to have control over the full import line like `from xy import z` instead of only the path.

Besides that, the new version works now imports the same class multiple times if it's selected multiple times.

**Comment by jsangmeister** [comment]
Oops, wrong button...

**Comment by ericbiewener** [comment]
Try this one. I've got that bug fixed that you mentioned and am actually calling `processImportPath` with the right arguments this time :)

The imported class is passed in [as the last argument](https://github.com/ericbiewener/vscode-vandelay/pull/32/files#diff-04c6e90faac2675aa89e2176d2eec7d8R153) to that function.

[vandelay-4.4.0.vsix - v2.zip](https://github.com/ericbiewener/vscode-vandelay/files/4439183/vandelay-4.4.0.vsix.-.v2.zip)
