### ISSUE TITLE
command 'vandelay.selectImport' not found

### ISSUE THREAD

**Issue by tabebqena** [ericbiewener/vscode-vandelay#33]
I tried to use the extension in python project. when I tried to use command "Import" I got error 
`Command 'Import...' resulted in an error (command 'vandelay.selectImport' not found)`

**Comment by ericbiewener** [comment]
Have you created a `vandelay-py.js` file at the root of your project?

**Comment by tabebqena** [comment]
Yes,

    `      
     const path = require('path')
     const src1 = path.join(__dirname, 'venv')
     const src2 = path.join(__dirname, 'academy')
     module.exports = {
        includePaths: [src1, src2],
        excludePatterns: [
             "**/*.test.*",
             '**/migrations/**/*.*',
             '**/management/commands/**/*.*',
             /.*\/config\/.*/,
        ],
        importGroups: [
          ['src1', 'src2'],
        ],
        maxImportLineLength: 120,
        processImportPath: importPath => (
        importPath.startsWith('academy')
            ? importPath.slice('my_packages.'.length)
            : importPath
        ),
        shouldIncludeImport: (absImportPath, activeFilepath) => (
          absImportPath.includes('__fixtures__') &&                     !activeFilepath.endsWith('.test.py')
          ),
          processImportName: (importName) => (importName === 'json' ? 'json as original_json' : null)
        }`

**Comment by tabebqena** [comment]
structure:

root:
      |
___academy
      |
___venv
      |
___vandelay-py.js

**Comment by ericbiewener** [comment]
Run the command "Toggle Developer Tools" to open the console, and the reload the window. I expect you'll see some kind of error about Vandelay not being able to initialize. Let me know.

**Comment by tabebqena** [comment]
DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/semver-umd/lib/semver-umd.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/xterm/lib/xterm.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/xterm-addon-unicode11/lib/xterm-addon-unicode11.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/xterm-addon-search/lib/xterm-addon-search.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/index.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/terminal.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/eventEmitter2.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/utils.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/ExperimentationService.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/FeatureProvider/TasApiFeatureProvider.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/FeatureProvider/FilteredFeatureProvider.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/FeatureProvider/BaseFeatureProvider.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/Util/AxiosHttpClient.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/ExperimentationServiceAutoPolling.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/ExperimentationServiceBase.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/Util/MemoryKeyValueStorage.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/Util/PollingService.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/semver-umd/lib/semver-umd.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/xterm/lib/xterm.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/xterm-addon-unicode11/lib/xterm-addon-unicode11.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/xterm-addon-search/lib/xterm-addon-search.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/index.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/terminal.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/eventEmitter2.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/node-pty/lib/utils.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/index.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/ExperimentationService.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/FeatureProvider/TasApiFeatureProvider.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/FeatureProvider/FilteredFeatureProvider.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/FeatureProvider/BaseFeatureProvider.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/Util/AxiosHttpClient.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/ExperimentationServiceAutoPolling.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/Util/MemoryKeyValueStorage.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/ExperimentationServiceBase.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///snap/code/43/usr/share/code/resources/app/node_modules.asar/tas-client/tas-client/Util/PollingService.js.map: 
    workbench.desktop.main.js:sourcemap:4248 Cannot register renderer for ms-python.python since it did not have an entrypoint. This is now required: https://github.com/microsoft/vscode/issues/102644
    (anonymous) @ workbench.desktop.main.js:sourcemap:4248
    _handle @ workbench.desktop.main.js:sourcemap:4215
    acceptUsers @ workbench.desktop.main.js:sourcemap:4215
    _handleExtensionPoint @ workbench.desktop.main.js:sourcemap:4574
    _doHandleExtensionPoints @ workbench.desktop.main.js:sourcemap:4573
    _startLocalExtensionHost @ workbench.desktop.main.js:sourcemap:5294
    _scanAndHandleExtensions @ workbench.desktop.main.js:sourcemap:5293
    async function (async)
    _scanAndHandleExtensions @ workbench.desktop.main.js:sourcemap:5292
    _initialize @ workbench.desktop.main.js:sourcemap:4569
    (anonymous) @ workbench.desktop.main.js:sourcemap:5285
    requestIdleCallback (async)
    t.runWhenIdle @ workbench.desktop.main.js:sourcemap:133
    (anonymous) @ workbench.desktop.main.js:sourcemap:5285
    Promise.then (async)
    W @ workbench.desktop.main.js:sourcemap:5285
    _createInstance @ workbench.desktop.main.js:sourcemap:1687
    _createServiceInstance @ workbench.desktop.main.js:sourcemap:1689
    _createServiceInstanceWithOwner @ workbench.desktop.main.js:sourcemap:1689
    _createAndCacheServiceInstance @ workbench.desktop.main.js:sourcemap:1688
    _getOrCreateServiceInstance @ workbench.desktop.main.js:sourcemap:1688
    get @ workbench.desktop.main.js:sourcemap:1686
    initLayout @ workbench.desktop.main.js:sourcemap:6736
    (anonymous) @ workbench.desktop.main.js:sourcemap:6807
    invokeFunction @ workbench.desktop.main.js:sourcemap:1686
    startup @ workbench.desktop.main.js:sourcemap:6807
    open @ workbench.desktop.main.js:sourcemap:7977
    async function (async)
    open @ workbench.desktop.main.js:sourcemap:7976
    t.main @ workbench.desktop.main.js:sourcemap:7981
    (anonymous) @ workbench.js:167
    async function (async)
    (anonymous) @ workbench.js:167
    (anonymous) @ bootstrap-window.js:93
    t._invokeFactory @ loader.js:1135
    t.complete @ loader.js:1135
    s._onModuleComplete @ loader.js:1712
    s._onModuleComplete @ loader.js:1712
    s._resolve @ loader.js:1647
    s.defineModule @ loader.js:1284
    r @ loader.js:1712
    c @ loader.js:795
    (anonymous) @ workbench.desktop.main.js:sourcemap:8003
    (anonymous) @ workbench.desktop.main.js:sourcemap:8003
    t._createAndEvalScript @ loader.js:795
    (anonymous) @ loader.js:795
    u @ loader.js:904
    (anonymous) @ loader.js:904
    readFileAfterClose @ internal/fs/read_file_context.js:61
    workbench.desktop.main.js:sourcemap:1706  WARN [File Watcher (chokidar)] Error: EIO: i/o error, lstat '/media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/academy/views/__pycache__/auth.cpython-38.pyc'
    workbench.desktop.main.js:sourcemap:284 [Extension Host] (node:68668) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    t.log @ workbench.desktop.main.js:sourcemap:284
    $logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:4546
    _doInvokeHandler @ workbench.desktop.main.js:sourcemap:4553
    _invokeHandler @ workbench.desktop.main.js:sourcemap:4553
    _receiveRequest @ workbench.desktop.main.js:sourcemap:4551
    _receiveOneMessage @ workbench.desktop.main.js:sourcemap:4550
    (anonymous) @ workbench.desktop.main.js:sourcemap:4548
    fire @ workbench.desktop.main.js:sourcemap:96
    fire @ workbench.desktop.main.js:sourcemap:452
    _receiveMessage @ workbench.desktop.main.js:sourcemap:457
    (anonymous) @ workbench.desktop.main.js:sourcemap:454
    fire @ workbench.desktop.main.js:sourcemap:96
    acceptChunk @ workbench.desktop.main.js:sourcemap:449
    (anonymous) @ workbench.desktop.main.js:sourcemap:448
    t @ workbench.desktop.main.js:sourcemap:458
    emit @ events.js:223
    addChunk @ _stream_readable.js:309
    readableAddChunk @ _stream_readable.js:290
    Readable.push @ _stream_readable.js:224
    onStreamRead @ internal/stream_base_commons.js:181
    workbench.desktop.main.js:sourcemap:284 [Extension Host] Vandelay activating
    workbench.desktop.main.js:sourcemap:284 [Extension Host] Unable to log remote console arguments Output omitted for an object that cannot be inspected ('Error: [edb.vandelay]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api edb.vandelay')
    workbench.desktop.main.js:sourcemap:284 [Extension Host] Loading vandelay config file from /media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/vandelay-js.js
    workbench.desktop.main.js:sourcemap:284 [Extension Host] Loading vandelay config file from /media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/vandelay-py.js
    workbench.desktop.main.js:sourcemap:284 [Extension Host] /media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/venv
    workbench.desktop.main.js:sourcemap:284 [Extension Host] Vandelay language registered: py
    workbench.desktop.main.js:sourcemap:4574 Activating extension 'edb.vandelay' failed: EIO: i/o error, stat '/media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/academy/views/__pycache__/auth.cpython-38.pyc'.
    _logMessageInConsole @ workbench.desktop.main.js:sourcemap:4574
    _logOrShowMessage @ workbench.desktop.main.js:sourcemap:4574
    $onExtensionActivationError @ workbench.desktop.main.js:sourcemap:4604
    _doInvokeHandler @ workbench.desktop.main.js:sourcemap:4553
    _invokeHandler @ workbench.desktop.main.js:sourcemap:4553
    _receiveRequest @ workbench.desktop.main.js:sourcemap:4551
    _receiveOneMessage @ workbench.desktop.main.js:sourcemap:4550
    (anonymous) @ workbench.desktop.main.js:sourcemap:4548
    fire @ workbench.desktop.main.js:sourcemap:96
    fire @ workbench.desktop.main.js:sourcemap:452
    _receiveMessage @ workbench.desktop.main.js:sourcemap:457
    (anonymous) @ workbench.desktop.main.js:sourcemap:454
    fire @ workbench.desktop.main.js:sourcemap:96
    acceptChunk @ workbench.desktop.main.js:sourcemap:449
    (anonymous) @ workbench.desktop.main.js:sourcemap:448
    t @ workbench.desktop.main.js:sourcemap:458
    emit @ events.js:223
    addChunk @ _stream_readable.js:309
    readableAddChunk @ _stream_readable.js:290
    Readable.push @ _stream_readable.js:224
    onStreamRead @ internal/stream_base_commons.js:181

**Comment by tabebqena** [comment]
To summerize, I think the following is specific for vanelay

    [Extension Host] Vandelay activating
    console.ts:137 [Extension Host] Unable to log remote console arguments Output omitted for an object that cannot be inspected ('Error: [edb.vandelay]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api edb.vandelay')
    console.ts:137 [Extension Host] Loading vandelay config file from /media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/vandelay-js.js
    console.ts:137 [Extension Host] Loading vandelay config file from /media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/vandelay-py.js
    console.ts:137 [Extension Host] /media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/venv
    console.ts:137 [Extension Host] Vandelay language registered: py
    abstractExtensionService.ts:416 Activating extension 'edb.vandelay' failed: EIO: i/o error, stat '/media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/academy/views/__pycache__/auth.cpython-38.pyc'.

**Comment by ericbiewener** [comment]
As part of the extension activation sequence, Vandelay does an initial caching of the available project exports. It appears to be erroring during this part of the process, specifically when looking at this file:

> /media/ahmad/2DD53B9005F868928/PROGRAM+/PROGRAMMING/flask_/academy2/academy/views/__pycache__/auth.cpython-38.pyc

My initial googling hasn't uncovered anything that can directly resolve this error -- I even see some people saying that `EIO: i/o error` might indicate a disk error of some kind. But perhaps simply deleting that file will solve the problem? It will obviously get regenerated at some point when you run your python program, but perhaps the regenerated version of the file will not throw this file system error.

If that doesn't work, a workaround would be to simply add a new `excludePattern` in order to skip all `*.pyc` files, i.e. `**/*.pyc`. That will prevent Vandelay from calling `fs.stat()` on the file, which should avoid the issue altogether.

**Comment by tabebqena** [comment]
It warked after editing `excludePatterns` in `vandelay-py.js` to:


 `
      excludePatterns: [
        "**/*.test.*",
        '**/migrations/**/*.*',
        '**/management/commands/**/*.*',
        /.*\/config\/.*/,
        "**/*.pyc",
        /.__pycache__.*/,

      ],
`

N.B:. Idon't know if this is necessary or not:
I did  `git rm --cached __`  for all __pycache__ folders and *.pyc files. It was added by error before installing the extension  .

**Comment by ericbiewener** [comment]
Glad it's working!
