### ISSUE TITLE
Command vandelay.selectImportForActiveWord not found

### ISSUE THREAD

**Issue by fusion-a** [ericbiewener/vscode-vandelay#36]
Hi, I just tried the extension out and I'm receiving the error from the title when trying to invoke the auto import with a custom shortcut in a python file. Do tell if I can provide more info (if the extension is still actively developed).
PS: I actually got the VSCode Pylance auto import to work

**Comment by ericbiewener** [comment]
I think you just misspelled the shortcut command. You wrote `vanedelay`. It should be `vandelay`.

**Comment by fusion-a** [comment]
I just misspelled it here on github. I used the key binding editor to set it up. Here's the entry:
```
{
  "key": "ctrl+shift+o",
  "command": "vandelay.selectImportForActiveWord"
}
```

**Comment by ericbiewener** [comment]
Did you create a vandelay-py.js file in the root of your project? Other than that, I'm not sure. Not really maintaining this project anymore. Best of luck!

**Comment by fusion-a** [comment]
Ah, no I didn't, I probably missed something in the readme, sorry for spamming the issue so hastily. I'll be using Pylints auto import anyway. Thanks for the response though, and best of luck to you too!
