### ISSUE TITLE
Struggling with setting includePaths

### ISSUE THREAD

**Issue by mnieber** [ericbiewener/vscode-vandelay#38]
First of all, I love this extension, it's essential for me.

However, I would like to put my vandelay files in a .vandelay subdirectory, and I cannot get this to work correctly. I'm currently trying like this. 

```
const path = require('path');
const baseDir = path.resolve(__dirname, '../src/');

module.exports = {
  // This is the only required property. At least one path must be included.
  includePaths: [baseDir],
  processImportPath: (importPath, absImportPath, activeFilepath, projectRoot) =>
    absImportPath.startsWith(projectRoot)
      ? absImportPath
          .slice(baseDir.length)
          .replace(/\.[^/.]+$/, '')
          .replaceAll('/', '.')
      : null,
};
```

For some reason, this doesn't work reliably, and I don't know why. I've tried different tricks, e.g. using environment variables, but the only thing that seems to work is a hard-coded path (which is not a portable option, or something I can commit to git).

**Comment by mnieber** [comment]
Actually, I just found out that using the hard-coded path also doesn't work reliably. After changing my vandelay file to use the hard-coded path again, I saved the file and got "Project exports have been cached" but nevertheless some newer imports were not found. I had to close vscode, reopen it, and save the vandelay file once more to have the latest exports in the cache.

**Comment by ericbiewener** [comment]
This project is no longer maintained. Feel free to fork it!
