### ISSUE TITLE
Does not find plugins on Windows

### ISSUE THREAD

**Issue by Erfa** [ericbiewener/vscode-vandelay#4]
I could not get this to work on Windows, has this been tested with Windows paths?

From what I can tell, the problem happens in `getProjectSettings` in `plugins.js`. The `absPath` was `\e:\<path-to-project>\vandelay-py.js`. Notice the forward slash in the beginning. When I removed it manually in the code it seems to work, but I'm not sure how this is best solved to keep it working on other platforms as well.

**Comment by mrozekma** [comment]
I ran into the same problem; looks like at [plugins.js:18](https://github.com/ericbiewener/vscode-vandelay/blob/911e3a68961419fcfc1a3883fa86f43f95989d80/src/plugins.js#L18) (and probably anywhere else you read that field) you want `fsPath` instead of `path`. On my Windows system `path` is `/c:/foo/bar` while `fsPath` is `c:\foo\bar`

**Comment by ericbiewener** [comment]
@mrozekma Good catch! I think I can safely update `.path` to `.fsPath` everywhere. I've got a [`windows`](https://github.com/ericbiewener/vscode-vandelay/pull/5) branch up if you two can pull that down and give it a test. To do that, just run `yarn install` and then `yarn ext`. That should overwrite whatever version of `vandelay-core` you currently have installed in your `.vscode/extensions` directory with the one from the `windows` branch. You'll then need to reload any open VS Code windows.

**Comment by mrozekma** [comment]
I can't install dependencies (it's trying to install event-stream 3.3.6, which is a bit [alarming](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)), and your `ext` command wouldn't work on Windows anyway, but I did try manually making those changes to my installed copy and it seems to be working fine

**Comment by ericbiewener** [comment]
Right, the `ext` command won't work on Windows. Struggling to get my mind out of unix :)

I'll try getting a new version published in the next couple days with the Windows changes and event-stream removed.

**Comment by ericbiewener** [comment]
Ok, update published that should work on Windows and not steal all your bitcoin.
