### ISSUE TITLE
command 'vandelay.***' not found

### ISSUE THREAD

**Issue by Divni** [ericbiewener/vscode-vandelay#6]
Tried installing it twice along with the Python plugin. Fully restarted vscode after install.

Any attempt to use the commands provided by vandelay gives an error saying "command vandelay.commandName not found".

vscode Version 1.32.3 (1.32.3)

**Comment by ericbiewener** [comment]
Do you have a [`vandelay-py.js`](https://github.com/ericbiewener/vscode-vandelay-py#configuration-vandelay-pyjs) in the root of your project? The extension won't activate if this file isn't found.
