### ISSUE TITLE
Command `Organize imports` not taking config into consideration 

### ISSUE THREAD

**Issue by karlAlnebratt** [ericbiewener/vscode-vandelay#9]
I have a config in my root `vandelay-js.js`
```javascript
const path = require('path')

module.exports = {
  includePaths: [
    path.join(__dirname, 'src'),
  ],
  excludePatterns: [
    '**/*.test.*',
    /.*\/__mock__\/.*/,
  ],
  maxImportLineLength: 10,
  useSemicolons: false,
  multilineImportStyle: 'single',
}

```

When I run `import` and `import active word` it takes my config in consideration and uses `  useSemicolons: false` `  multilineImportStyle: 'single'`

But when I run `Organize imports` it puts all my miports on the same line and adds a semicolon to the end.

**Comment by ericbiewener** [comment]
`Organize Imports` is actually a built-in VS Code command, not one provided by Vandelay. I have considered adding this functionality to Vandelay, but am not sure how concerned people tend to be about this sort of thing. The uptake of tools like Prettier and Black (python) are making the formatting features of Vandelay less necessary.

**Comment by karlAlnebratt** [comment]
Ok, thanks for the info.
And thanks for a very nice plugin.
